### ISSUE TITLE
Add a "Posted by" filter

### ISSUE THREAD

**Issue by K9ZMD** [azerupi/SOTAwatch-filter#20]
Treating SOTAwatch like a sked page or chat room clutters the page and pushes useful spots out of sight.  Creating a "Posted by" filter would enable us to hide posts by those who consistently misuse SOTAwatch in this (or any other) manner.

**Comment by azerupi** [comment]
Hi,

Actually you can already do this. You can filter for **Posted by** in the _comment include and exclude box_. I tried to keep the settings page a little less crowded by unifying those 2 filters ;)

I am aware it is not (well) documented and I should rework the docs someday.

Cheers,

Mathieu

**Comment by K9ZMD** [comment]
Mathieu, thank you for the reply.  

Well, that is embarrassing and I am sorry for posting my suggestion too quickly.  It did not occur to me yesterday to enter just the offender's call sign in the Comments filter.  My experiments failed because I complicated matters by trying to exclude the entire phrase in various ways, i.e. Posted by W1XX . . . (Posted by K2YY) . . .  |Posted by N3ZZ| 

73, and once again my apologies.

Gary

"Better to remain silent and be thought a fool than to speak out and remove all doubt."
Abraham Lincoln

**Comment by azerupi** [comment]
I can understand. It's not documented, so it's not your fault :wink: 
And don't worry, it's nice to have feedback. At least I know my work is useful.

Have nice day,

Mathieu
