### ISSUE TITLE
Filter (too much)

### ISSUE THREAD

**Issue by ik2yra** [azerupi/SOTAwatch-filter#23]
Hello, i made a filter to avoid spot from europe, filtering usa vk and zl. but i don't know why ignores spots from LA. Can someone tell me what i'm doing wrong? 
attach two screen shots.
[SotawatchFilterBug.docx](https://github.com/azerupi/SOTAwatch-filter/files/177670/SotawatchFilterBug.docx)

tks 73 de ik2yra

**Comment by ChristopheDavid** [comment]
Your regular expression is invalid.

Try ^(vk|zl|[nawkj])  or   ^(vk|zl|n|a|w|k|j)

See http://www.regular-expressions.info/quickstart.html for details.

73 de on6zq

**Comment by ik2yra** [comment]
Ok,  thanks. I will try.
73's Carlos IK2YRA.
Il 17/mar/2016 12:48, "Christophe David" notifications@github.com ha
scritto:
